export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const POST_REQUEST = "POST_REQUEST";
export const POST_FAIL = "POST_FAIL";
export const POST_SUCCESS = "POST_SUCCESS";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

export const DELETE_POST_REQ = "DELETE_POST_REQ";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const EDIT_POST_REQ = "EDIT_POST_REQ";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAIL = "EDIT_POST_FAIL";
